services:
  - type: web
    name: requisicoes-xodo
    env: python
    pythonVersion: 3.10.14

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn requisicoes.wsgi:application

    autoDeploy: true

    envVars:
      DJANGO_SETTINGS_MODULE: requisicoes.settings

    # Onde o Render vai servir arquivos est√°ticos
    staticPublishPath: staticfiles
