services:
  - type: web
    name: requisicoes-xodo
    env: python
    runtime: python3.10
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn requisicoes.wsgi:application
