services:
  - type: web
    name: requisicoes-xodo
    env: python
    pythonVersion: 3.10.14
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn requisicoes.wsgi:application
    staticPublishPath: staticfiles
