services:
  - type: web
    name: requisicoes-xodo
    runtime: python
    env: python3.10
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn requisicoes.wsgi:application"
    autoDeploy: true
