services:
  - type: web
    name: requisicoes-xodo
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn requisicoes.wsgi:application"
    autoDeploy: true
